import { IRoute } from "@bluelibs/x-ui";
import "./i18n";

import {
  STARSHIP_MEMBERS_LIST as BASE_STARSHIP_MEMBERS_LIST,
  STARSHIP_MEMBERS_CREATE as BASE_STARSHIP_MEMBERS_CREATE,
  STARSHIP_MEMBERS_EDIT as BASE_STARSHIP_MEMBERS_EDIT,
  STARSHIP_MEMBERS_VIEW as BASE_STARSHIP_MEMBERS_VIEW,
} from "./config/routes";

export const STARSHIP_MEMBERS_LIST: IRoute = {
  ...BASE_STARSHIP_MEMBERS_LIST,
};

export const STARSHIP_MEMBERS_CREATE: IRoute = {
  ...BASE_STARSHIP_MEMBERS_CREATE,
};

export const STARSHIP_MEMBERS_EDIT: IRoute = {
  ...BASE_STARSHIP_MEMBERS_EDIT,
};

export const STARSHIP_MEMBERS_VIEW: IRoute = {
  ...BASE_STARSHIP_MEMBERS_VIEW,
};
